import { Client } from "@notionhq/client";
import { PageObjectResponse, QueryDatabaseResponse } from "@notionhq/client/build/src/api-endpoints";

const notion = new Client({
  auth: process.env.NOTION_API_KEY,
});

const DATABASE_ID = process.env.NOTION_DATABASE_ID || "";

interface SessionData {
  id: string; // This is the Notion page ID (generated by Notion)
  Problem: string;
  Context: string;
  "Active Models": string[];
  "Selected AI Model": string;
  Timestamp: number;
  Insights: string;
  InsightsModelsUsed: string[];
  "Key Factors": string[];
  KeyFactorsModelsUsed: string[];
  Recommendation: string;
  RecommendationModelsUsed: string[];
  "Case Studies": Array<{
    title: string;
    description: string;
    outcome: string;
    appliedModels: string;
    modelsUsed: string[];
  }>;
  "Canvas Items": any; // Will be stringified JSON
  "Soul Questions": {
    yesQuestions: string[];
    noQuestions: string[];
    modelsUsed: string[];
  };
  "Pro Con": {
    option1: {
      title: string;
      pros: Array<{ text: string; weight: string }>;
      cons: Array<{ text: string; weight: string }>;
    };
    option2: {
      title: string;
      pros: Array<{ text: string; weight: string }>;
      cons: Array<{ text: string; weight: string }>;
    };
    modelsUsed: string[];
  };
  Simulator: {
    option1Title: string;
    option2Title: string;
    parameters: Array<{
      name: string;
      description: string;
      impact: string;
    }>;
    recommendation: string;
    modelsUsed: string[];
  };
  "First Principles": {
    explanation: string;
    problemApplication: {
      question1: string;
      answer1: string;
      question2: string;
      answer2: string;
      question3: string;
      answer3: string;
      solution: string;
    };
    modelsUsed: string[];
  };
}

// Helper to convert Notion properties to our SessionData format
function mapNotionPropertiesToSession(page: PageObjectResponse): SessionData {
  const properties = page.properties;

  const getPropertyValue = (propName: string, type: string) => {
    const prop = properties[propName];
    if (!prop) return undefined;

    switch (type) {
      case 'title': return (prop as any).title?.[0]?.plain_text || "";
      case 'rich_text': return (prop as any).rich_text?.[0]?.plain_text || "";
      case 'multi_select': return (prop as any).multi_select?.map((s: any) => s.name) || [];
      case 'select': return (prop as any).select?.name || "";
      case 'number': return (prop as any).number || 0;
      case 'date': return (prop as any).date?.start ? new Date((prop as any).date.start).getTime() : 0; // Convert date string back to timestamp
      default: return undefined;
    }
  };

  const parseJsonField = (propName: string) => {
    const prop = properties[propName];
    if (!prop) return null;
    const jsonString = (prop as any).rich_text?.[0]?.plain_text;
    try {
      return jsonString ? JSON.parse(jsonString) : null;
    } catch (e) {
      // console.error(`Failed to parse JSON for ${propName}:`, jsonString, e);
      return null;
    }
  };

  return {
    id: page.id, // Use the actual Notion page ID
    Problem: getPropertyValue("Problem", "title") as string,
    Context: getPropertyValue("Context", "rich_text") as string,
    "Active Models": getPropertyValue("Active Models", "multi_select") as string[],
    "Selected AI Model": getPropertyValue("Selected AI Model", "select") as string,
    Timestamp: getPropertyValue("Timestamp", "date") as number, // Use 'date' type for retrieval
    Insights: getPropertyValue("Insights", "rich_text") as string,
    InsightsModelsUsed: parseJsonField("InsightsModelsUsed") || [],
    "Key Factors": (getPropertyValue("Key Factors", "rich_text") as string)?.split(', ').filter(Boolean) || [],
    KeyFactorsModelsUsed: parseJsonField("KeyFactorsModelsUsed") || [],
    Recommendation: getPropertyValue("Recommendation", "rich_text") as string,
    RecommendationModelsUsed: parseJsonField("RecommendationModelsUsed") || [],
    "Case Studies": parseJsonField("Case Studies") || [],
    "Canvas Items": parseJsonField("Canvas Items"),
    "Soul Questions": parseJsonField("Soul Questions"),
    "Pro Con": parseJsonField("Pro Con"),
    Simulator: parseJsonField("Simulator"),
    "First Principles": parseJsonField("First Principles"),
  };
}

// Helper to convert SessionData to Notion properties format (omitting 'id' as Notion generates it)
function mapSessionToNotionProperties(session: Omit<SessionData, 'id'>) {
  return {
    "Problem": { type: "title", title: [{ type: "text", text: { content: session.Problem } }] },
    "Context": { type: "rich_text", rich_text: [{ type: "text", text: { content: session.Context } }] },
    "Active Models": { type: "multi_select", multi_select: session["Active Models"].map(name => ({ name })) },
    "Selected AI Model": { type: "select", select: { name: session["Selected AI Model"] } },
    "Timestamp": { type: "date", date: { start: new Date(session.Timestamp).toISOString() } },
    "Insights": { type: "rich_text", rich_text: [{ type: "text", text: { content: session.Insights } }] },
    "InsightsModelsUsed": { type: "rich_text", rich_text: [{ type: "text", text: { content: JSON.stringify(session.InsightsModelsUsed) } }] },
    "Key Factors": { type: "rich_text", rich_text: [{ type: "text", text: { content: session["Key Factors"].join(", ") } }] },
    "KeyFactorsModelsUsed": { type: "rich_text", rich_text: [{ type: "text", text: { content: JSON.stringify(session.KeyFactorsModelsUsed) } }] },
    "Recommendation": { type: "rich_text", rich_text: [{ type: "text", text: { content: session.Recommendation } }] },
    "RecommendationModelsUsed": { type: "rich_text", rich_text: [{ type: "text", text: { content: JSON.stringify(session.RecommendationModelsUsed) } }] },
    "Case Studies": { type: "rich_text", rich_text: [{ type: "text", text: { content: JSON.stringify(session["Case Studies"]) } }] },
    "Canvas Items": { type: "rich_text", rich_text: [{ type: "text", text: { content: JSON.stringify(session["Canvas Items"]) } }] },
    "Soul Questions": { type: "rich_text", rich_text: [{ type: "text", text: { content: JSON.stringify(session["Soul Questions"]) } }] },
    "Pro Con": { type: "rich_text", rich_text: [{ type: "text", text: { content: JSON.stringify(session["Pro Con"]) } }] },
    "Simulator": { type: "rich_text", rich_text: [{ type: "text", text: { content: JSON.stringify(session.Simulator) } }] },
    "First Principles": { type: "rich_text", rich_text: [{ type: "text", text: { content: JSON.stringify(session["First Principles"]) } }] },
  };
}

export async function saveSessionToNotion(session: Omit<SessionData, 'id'>) { // Expect session without 'id'
  try {
    // Create the page - Notion will automatically assign an ID
    const createResponse = await notion.pages.create({
      parent: { database_id: DATABASE_ID },
      properties: mapSessionToNotionProperties(session),
    });

    // Update the newly created page to set its own ID into the "App Session ID" property
    await notion.pages.update({
      page_id: createResponse.id,
      properties: {
        "App Session ID": { // This property must exist in your Notion database as a Text type
          type: "rich_text",
          rich_text: [{ type: "text", text: { content: createResponse.id } }],
        },
      },
    });

    // Return the original create response, which contains the page ID
    return createResponse;
  } catch (error) {
    console.error("Error saving session to Notion:", error);
    throw error;
  }
}

export async function getSessionsFromNotion(): Promise<SessionData[]> {
  try {
    const response: QueryDatabaseResponse = await notion.databases.query({
      database_id: DATABASE_ID,
      sorts: [{ property: "Timestamp", direction: "descending" }],
    });

    return response.results
      .filter((page): page is PageObjectResponse => "properties" in page)
      .map(mapNotionPropertiesToSession);
  } catch (error) {
    console.error("Error fetching sessions from Notion:", error);
    throw error;
  }
}

export async function getSingleSessionFromNotion(pageId: string): Promise<SessionData | null> {
  try {
    const response = await notion.pages.retrieve({ page_id: pageId });
    if ("properties" in response) {
      return mapNotionPropertiesToSession(response);
    }
    return null;
  } catch (error) {
    console.error(`Error fetching session ${pageId} from Notion:`, error);
    return null;
  }
}

export async function deleteSessionFromNotion(pageId: string) {
  try {
    const response = await notion.pages.update({
      page_id: pageId,
      archived: true, // Notion API recommends archiving instead of deleting
    });
    console.log("Session archived in Notion:", response);
    return response;
  } catch (error) {
    console.error("Error deleting session from Notion:", error);
    throw error;
  }
}